### PR TITLE
Use taobao timestamp service instead of jd

### PR DESCRIPTION
**Pull request by chengweiv5**
Fix #4

Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>

### CODE REVIEW

**Comment by skyiea314** [comment]
https://api.m.jd.com/client.action?functionId=queryMaterialProducts&client=wh5

**Comment by skyiea314** [comment]
京东最新的时间获取地址:https://api.m.jd.com/client.action?functionId=queryMaterialProducts&client=wh5
将timer.py 中第31行的url替换为这个就可以了

**Comment by chengweiv5** [comment]
> https://api.m.jd.com/client.action?functionId=queryMaterialProducts&client=wh5

赞，直接提交一个 PR 吗？

**Comment by chengweiv5** [comment]
看到了， #2

**Pull request closed without merging**
